spring.application.name=demo
springdoc.swagger-ui.url=/openapi.yml
spring.jpa.hibernate.ddl-auto=update
spring.config.import=optional:file:.env[.properties]
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:seed}
server.port=${PORT:8080}
server.ssl.enabled=false
max.pagination.size=100
